version: '3'
services:
    site:
        build: .
        ports :
            - "8080:80"
        volumes:
            - ./:/var/www/html/
        links:
            - database
    database:
        image: mysql:5.5
        ports:
            - "3333:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        command: mysqld --sql_mode="IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        volumes:
            - ./data:/var/lib/mysql
    php-myadmin:
        image: corbinu/docker-phpmyadmin
        ports:
            - "8081:80"
        environment:
            - MYSQL_USERNAME=user
            - MYSQL_PASSWORD=password
            - MYSQL_PORT_3306_TCP_ADDR=mysql
        links:
            - database:mysql
